language: python

sudo: required
python:
  - "3.4"

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

before_script:
  - docker-compose build

script:
  - docker-compose run acme-dao test
